config/routes.rb
Rails.application.routes.draw do
  resources :photos

  devise_for :users

  get'users/' => 'high_voltage/pages#show', id: 'account'

resources :listings do 
  resources :photos
end

end

app/models/listing.rb
class Listing < ActiveRecord::Base
	#attr_accessor :listing_id

	belongs_to :user
	has_many :photos, :dependent => :destroy

	accepts_nested_attributes_for :photos, :reject_if => lambda { |t| t['photo'].nil? }
end

app/models/photo.rb
class Photo < ActiveRecord::Base
	#attr_accessor :image, :listing_id
	# attr_accessor :photos_attributes

	belongs_to :listing

	has_attached_file :image, :styles => { :large => "800>x500", :thumb => "100x100>" }, :default_url => "/images/:style/missing.png"
	validates_attachment_content_type :image, :content_type => /\Aimage\/.*\Z/
	validates_presence_of :image
end

app/models/user.rb
class User < ActiveRecord::Base


	has_many :listings
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_attached_file :avatar, :styles => { :medium => "300x300>", :thumb => "100x100>" }, :default_url => "/images/:style/missing.png"
  validates_attachment_content_type :avatar, :content_type => /\Aimage\/.*\Z/
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  def after_sign_in_path_for(resource)
  	users_path
  end


  before_filter :configure_permitted_parameters, if: :devise_controller?


  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.for(:account_update) << :avatar
    devise_parameter_sanitizer.for(:account_update) << :address
    devise_parameter_sanitizer.for(:account_update) << :website
    devise_parameter_sanitizer.for(:account_update) << :phone
    devise_parameter_sanitizer.for(:account_update) << :title
    devise_parameter_sanitizer.for(:account_update) << :name

  end
end

app/controllers/listings_controller.rb
class ListingsController < ApplicationController
  before_action :set_listing, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, :except => [:show]
  

  # GET /listings
  # GET /listings.json
  def index
    @listings = Listing.all
  end

  # GET /listings/1
  # GET /listings/1.json
  def show

  end

  # GET /listings/new
  def new
    @listing = Listing.new
    4.times {@listing.photos.build}
    
  end

  def house_num

  end

  # GET /listings/1/edit
  def edit
  end

  # POST /listings
  # POST /listings.json
  def create
    @listing = Listing.new(listing_params)

    if user_signed_in?
      @listing.user_id = current_user.id
    end


    respond_to do |format|
      if @listing.save

        params['listing']['photos_attributes'].each do |i|

        #photo_params = listing_params['photos_attributes'][i]['image'] rescue nil
        photo_params = i[1]['image']
        #binding.pry
        @photo = Photo.create(image: photo_params, listing_id: @listing.id)
        
        end
        if @photo.save
          format.html { redirect_to @listing, notice: 'Listing was successfully created.' }
          format.json { render :show, status: :created, location: @listing }
        else
          format.html { render :new }
          format.json { render json: @listing.errors, status: :unprocessable_entity }
        
        
        end
      else
        format.html { render :new }
        format.json { render json: @listing.errors, status: :unprocessable_entity }
      
      end
    end
  end

  # PATCH/PUT /listings/1
  # PATCH/PUT /listings/1.json
  def update
    respond_to do |format|
      if @listing.update(listing_params)
        format.html { redirect_to @listing, notice: 'Listing was successfully updated.' }
        format.json { render :show, status: :ok, location: @listing }
      else
        format.html { render :edit }
        format.json { render json: @listing.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /listings/1
  # DELETE /listings/1.json
  def destroy
    @listing.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'Listing was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_listing
      @listing = Listing.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def listing_params
      params.require(:listing).permit(:house_num, :address, :price, :description, :details, :user_id, photos_attributes: [:image, :listing_id])
    end
end

app/controllers/photos_controller.rb
class PhotosController < ApplicationController
    before_action :set_photo, only: [:show, :edit, :update, :destroy]

	def new
    @photo = Photo.new
    end

    def show
    end


	def create
    @photo = Photo.create(photo_params)
    @photo.listing = @listing
    end

  def create
    
    @photo = Photo.new(photo_params)
    # @listing.photos.build
   

    respond_to do |format|
      if @photo.save
        format.html { redirect_to @photo, notice: 'Photo was successfully created.' }

      else
        format.html { render :new }
        format.json { render json: @photo.errors, status: :unprocessable_entity }
      end
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_photo
      @photo = Photo.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def photo_params
      params.require(:photo).permit(:image, :listing_id)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/listings_helper.rb
module ListingsHelper
end

app/views/layouts/_head.html.erb
<title>Final</title>

  <link href="http://netdna.bootstrapcdn.com/font-awesome/4.0.3/css/font-awesome.css" rel="stylesheet">
    <link href="http://netdna.bootstrapcdn.com/bootswatch/3.1.1/flatly/bootstrap.min.css" rel="stylesheet">


						

    <script src="http://ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js"></script>


	
    <script src="//netdna.bootstrapcdn.com/bootstrap/3.1.1/js/bootstrap.min.js"></script>



    <script src='http://ajax.googleapis.com/ajax/libs/jquery/1.8.2/jquery.min.js'></script>
   
  
  
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
 

  <%= csrf_meta_tags %> 

app/views/layouts/_header.html.erb
<div class="navbar navbar-default">
                <div class="navbar-header">
                  <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-responsive-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                  </button>
                  <!-- <a class="navbar-brand" href="#">Cool Co Logo</a> -->
                  <%= image_tag "logo.png", {:class => 'logo'} %>
                </div>
                <div class="navbar-collapse collapse navbar-responsive-collapse">
                 <!--  <ul class="nav navbar-nav">
                    <li class="active"><a href="#">Active</a></li>
                    <li><a href="#">Link</a></li>
                    <li class="dropdown">
                      <a href="#" class="dropdown-toggle" data-toggle="dropdown">Dropdown <b class="caret"></b></a>
                      <ul class="dropdown-menu">
                        <li><a href="#">Action</a></li>
                        <li><a href="#">Another action</a></li>
                        <li><a href="#">Something else here</a></li>
                        <li class="divider"></li>
                        <li class="dropdown-header">Dropdown header</li>
                        <li><a href="#">Separated link</a></li>
                        <li><a href="#">One more separated link</a></li>
                      </ul>
                    </li>
                  </ul> -->

                  <ul class="nav navbar-nav navbar-right">
                    
                    <% if user_signed_in? %>

                      <li class="dropdown">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown">My Account<b class="caret"></b></a>

                        
                  

                      <ul class="dropdown-menu">
                        <li><%= link_to 'Home', users_path %></li>
                        <li><%= link_to 'Settings', edit_user_registration_path %></li>
                        <li class="divider"></li>
                        <li><%= link_to 'Sign Out', destroy_user_session_path, :method => 'delete' %></li>
                      </ul>
                    </li>

                     

                    <% else %>
                    
                    <li><%= link_to 'Sign In', new_user_session_path %></li>
                    <% end %>
                  </ul>

                  
                </div>
              </div>

app/views/layouts/_listing_head.html.erb
<title>Final - Listing</title>


<link href="/assets/reset.css" rel="stylesheet">
<script src='http://ajax.googleapis.com/ajax/libs/jquery/1.8.2/jquery.min.js'></script>

<link href='http://fonts.googleapis.com/css?family=Open+Sans:400italic,300,400,700' rel='stylesheet' type='text/css'>




 <%= javascript_include_tag 'main', 'data-turbolinks-track' => false %>
  <%= javascript_include_tag 'jquery.bxslider.min.js', 'data-turbolinks-track' => false %>

  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => false %>
<%= stylesheet_link_tag    'listings', 'data-turbolinks-track' => false %>

  

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <% if params[:action] == ('show') && params[:controller] == ('listings') %>
    <%= render 'layouts/listing_head' %>
  <% else %>
    <%= render 'layouts/head' %>
  <% end %>

</head>
<body>

  <% if params[:action] == ('show') && params[:controller] == ('listings') %>

    <%= yield %>
  
  <% elsif current_page?(root_url) %>
  
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
    <div class='container'>
      <%= yield %>
    </div>

  <% else %>
  <%= render 'layouts/header' %>
  
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
<div class='container'>
<%= yield %>
</div>
  <% end %>

</body>
</html>

app/views/listings/_form.html.erb
<div class="listing-form">

<%= form_for @listing, :html => {:multipart => true} do |f| %>
  <% if @listing.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@listing.errors.count, "error") %> prohibited this listing from being saved:</h2>

      <ul>
      <% @listing.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

 <div class="field">
    <%= f.label "House number" %><br>
    <%= f.text_field :house_num %>
  </div>

  <div class="field">
    <%= f.label :address %><br>
    <%= f.text_field :address %>
  </div>
  <div class="field">
    <%= f.label :price %><br>
    <%= f.text_field :price %>
  </div>
  <div class="field text">
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </div>
  <br>
  <div class="field text">
    <%= f.label :details %><br>
    <%= f.text_area :details %>
  </div>
  <br>
 
  


 <div class="field images">
  <label>Images</label>
 <%= f.fields_for :photos do |builder| %>
   
   
  
   <%= builder.file_field :image %>
   
  <% end %>
</div>

  <div class="actions">
    <%= f.submit %>
  
  </div>

<% end %>
</div> <!-- listing form -->

app/views/listings/index.html.erb
<h1>Listing listings</h1>

<table>
  <thead>
    <tr>
      <th>Address</th>
      <th>Price</th>
      <th>Description</th>
      <th>Details</th>
      <th>User</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @listings.each do |listing| %>
      <tr>
        <td><%= listing.address %></td>
        <td><%= listing.price %></td>
        <td><%= listing.description %></td>
        <td><%= listing.details %></td>
        <td><%= listing.user_id %></td>
        <td><%= link_to 'Show', listing %></td>
        <td><%= link_to 'Edit', edit_listing_path(listing) %></td>
        <td><%= link_to 'Destroy', listing, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Listing', new_listing_path %>

app/views/listings/new.html.erb
<h1 class="center">New listing</h1>

<%= render 'form' %>

<%= link_to 'Back', listings_path %>

app/views/listings/show.html.erb
	
	<div class="header">
		<h1 class="address"><span class="house-num"> <%= @listing.house_num %><br></span><%= @listing.address %></h1>
	</div><!-- header -->
	<div class="wrapper">
	<div class="content first">
		
	
	 	<div class="image"> 
			<ul class="bxslider">
				
				<% @listing.photos.each do |photo| %>
				<li><%= image_tag photo.image.url(:large)  %></li>
				
				<% end %>
				
			</ul>
			
		</div><!-- images -->

		<div class="price">
		<p class="price">$<%= @listing.price %></p>
	</div>
		<div class="description half pull-left">
			<h3>Description</h3>
			<%= @listing.description.html_safe %>

			
		</div><!-- description -->
		<div class="details half pull-right">
			<h3>Details</h3>
			<%= @listing.details.html_safe %>
		</div><!-- details -->
		

	</div><!-- content -->
	</div><!-- wrapper -->

	<div class="agent">
		<div class="content">
		<h3 class="pull-left"><%= @listing.user.name %> - <span class="title"><%= @listing.user.title %></span></h3>
        			
					
					<span class="phone"><%= @listing.user.phone %></span>
        			<address class="pull-right">
        				<%= @listing.user.address %>
        			</address>
        </div><!-- content -->			
	</div><!-- agent -->

app/views/listings/show2.html.erb
<!-- <p id="notice"><%= notice %></p> -->

<p>
  <strong>Address:</strong>
  <%= @listing.address %>
</p>

<p>
  <strong>Price:</strong>
  <%= @listing.price %>
</p>

<p>
  <strong>Description:</strong>
  <%= @listing.description %>
</p>

<p>
  <strong>Details:</strong>
  <%= @listing.details %>
</p>

<p>
  <strong>User:</strong>
  <%= @listing.user_id %>
</p>

<p>
  <strong>Image:</strong>
  
  <% @listing.photos.each do |photo| %>
    <%= image_tag photo.image %>
  <% end %>


</p>



<%= link_to 'Edit', edit_listing_path(@listing) %> |
<%= link_to 'Back', listings_path %>

app/views/pages/account.html.erb
<div class="row row-one">

	<div class="col-md-5"><h3>
		Welcome, <%= current_user.name %>
	</h3></div>
	<div class="col-md-5 col-md-offset-2">
		<button type="button" class="btn btn-success btn-lg pull-right"><%= link_to 'New Listing ', new_listing_path %> <i class="fa fa-plus"></i></button>
	</div>

</div><!-- row-one -->

<div class="row row-two">

	<div class="col-md-12">
		<h2>Current Listings:</h2>

		<table>
  <thead>
    <tr>
      <th>Address</th>
      
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
   <% current_user.listings.each do |listing| %>
      <tr>
        <td><%= listing.address %></td>
       
        <td><%= link_to 'Show', listing_path(listing) %></td>
        <td><%= link_to 'Edit', edit_listing_path(listing) %></td>
        <td><%= link_to 'Delete', listing_path(listing), method: :delete, data: { confirm: 'Are you certain you want to delete this?' } %></td>
        
      </tr>
    <% end %>
  </tbody>
</table>

		

	</div>

</div><!-- row-two -->

app/views/pages/index.html.erb
<ul class="pull-right home-links">
	                    <% if user_signed_in? %>
                 
                        <li><%= link_to 'My Account', users_path %></li>
                    
                    	<% else %>
                    
                    	<li><%= link_to 'Sign In', new_user_session_path %></li>
                    	<li><%= link_to 'Sign Up',  new_user_registration_path %></li>
                    	<% end %>
</ul>

	<h1>Welcome to RealtyApp</h1>
	<h2>Create beautiful websites for your listings</h2>
	<button type="button" class="btn btn-success btn-lg"><%= link_to 'New Listing ', new_listing_path %><i class="fa fa-plus"></i></button>

app/views/pages/profile.html.erb
<div class="row">
	<h2>Your Profile</h2>


	<%= form_for(current_user) do |f| %>
  <% if current_user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(current_user.errors.count, "error") %> prohibited this profile from being saved:</h2>

      <ul>
      <% current_user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :address %><br>
    <%= f.text_area :address %>
  </div>
  <div class="field">
    <%= f.label :phone %><br>
    <%= f.text_field :phone %>
  </div>
  <div class="field">
    <%= f.label :website %><br>
    <%= f.text_field :website %>
  </div>
  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

</div>

app/views/pages/show.html.erb
	
	<div class="header">
		<h1 class="address"><span class="house-num">100 <br></span><%= @listing.address %></h1>
	</div><!-- header -->
	<div class="wrapper">
	<div class="content first">
		

	 	<div class="image"> 
			<ul class="bxslider">
				<!-- <li><img src="/images/pic1.jpg" /></li>
				<li><img src="/images/pic2.jpg" /></li>
				<li><img src="/images/pic3.jpg" /></li> -->
				<li><img src="http://placehold.it/900x458" /></li>
				<li><img src="http://placehold.it/900x458" /></li>
				<li><img src="http://placehold.it/900x458" /></li>
				<li><img src="http://placehold.it/900x458" /></li>
			</ul>
			
		</div><!-- images -->
		<div class="description half pull-left">
			<h3>Description</h3>
			<p><%= @listing.description %></p>

			
		</div><!-- description -->
		<div class="details half pull-right">
			<h3>Details</h3>
			<p><%= @listing.details %></p>
		</div><!-- details -->
		

	</div><!-- content -->
	</div><!-- wrapper -->

	<div class="agent">
		<div class="content">
		<h3 class="pull-left"><%= @listing.user.name %> - <span class="title"><%= @listing.user.title %></span></h3>
        			
					
					<span class="phone"><%= @listing.user.phone %></span>
        			<address class="pull-right">
        				<%= @listing.user.address %>
        			</address>
        </div><!-- content -->			
	</div><!-- agent -->

app/views/photos/_form.html.erb
<%= form_for @photo, :html => {:multipart => true} do |f| %>
  <% if @photo.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@photo.errors.count, "error") %> prohibited this photo from being saved:</h2>

      <ul>
      <% @photo.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>



  
 <div><%= f.label :image %> <i>Upload you photo</i><br />
  <%= f.file_field :image %></div>


  <div class="actions">
    <%= f.submit %>
  
  </div>

<% end %>

app/views/photos/edit.html.erb
<h1>Editing listing</h1>

<%= render 'form' %>

<%= link_to 'Show', @listing %> |
<%= link_to 'Back', listings_path %>

app/views/photos/index.html.erb
<h1>Listing Photos</h1>

<table>
  <thead>
    <tr>
      <th>Image</th>
      
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @photos.each do |photo| %>
      <tr>
        <td><%= photo.image %></td>
        <td><%= photo.listing_id %></td>
        <td><%= link_to 'Show', photo %></td>
        <td><%= link_to 'Edit', edit_photo_path(photo) %></td>
        <td><%= link_to 'Destroy', photo, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New photo', new_photo_path %>

app/views/photos/new.html.erb
<h1>New listing</h1>

<%= render 'form' %>

<%= link_to 'Back', listings_path %>

app/views/photos/show.html.erb
<p id="notice"><%= notice %></p>



<p>
  <strong>Image:</strong>
  <%= image_tag @photo.image.url %>


</p>



<%= link_to 'Edit', edit_photo_path(@photo) %> |
<%= link_to 'Back', photo_path %>